name: Build with Gradle

on:
  workflow_dispatch:
  push:

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=false'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout development
      uses: actions/checkout@v2
      with:
        ref: 'development'

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Build
      run: ./gradlew --stacktrace lintSnapshotBasicRelease assembleSnapshotBasicDebug

    - name: Upload apk
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: tables_app-snapshot-basic-debug.apk
        path: tables_app/build/outputs/apk/snapshotBasic/debug/tables_app-snapshot-basic-debug.apk
        if-no-files-found: error

    - name: Upload lint results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: lint-results
        path: tables_app/build/reports/lint-results-*
        if-no-files-found: error

  connected-test:
    needs: build
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        api: [23]

    steps:
    - name: Checkout development
      uses: actions/checkout@v2
      with:
        #ref: 'development'
        path: tables

    - name: Checkout Services
      uses: actions/checkout@v2
      with:
        repository: odk-x/services
        ref: development
        path: services

    - name: Checkout Survey
      uses: actions/checkout@v2
      with:
        repository: odk-x/survey
        ref: development
        path: survey

    - name: Checkout Application Designer
      uses: actions/checkout@v2
      with:
        repository: odk-x/app-designer
        ref: development
        path: app-designer

    - name: Checkout OI File Manager
      uses: actions/checkout@v2
      with:
        repository: openintents/filemanager
        ref: 2.3.1
        path: filemanager

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Set up app-designer
      working-directory: app-designer
      run: |
        npm install grunt-cli
        npm ci

    # Work around a bug in this action
    # 28 requires the same licence as 30
    - name: Set up licence for API 28
      uses: reactivecircus/android-emulator-runner@v2
      if: ${{ matrix.api == 28 }}
      with:
        api-level: 30
        target: google_apis
        script: echo 1

    - name: Run connectedSnapshotUitestDebugAndroidTest
      uses: reactivecircus/android-emulator-runner@v2
      timeout-minutes: 60
      with:
        working-directory: tables
        api-level: ${{ matrix.api }}
        target: google_apis
        sdcard-path-or-size: 1024M
        profile: Nexus 7
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -memory 2048
        script: |
          adb logcat > logcat.log 2>&1 &
          cd ../services     && ./gradlew --stacktrace installSnapshotBasicDebug
          cd ../survey       && ./gradlew --stacktrace installSnapshotBasicDebug
          # adb install ../filemanager.apk
          cd ../filemanager  && ./gradlew :FileManager:installPlayDebug
          ../app-designer/node_modules/.bin/grunt --gruntfile ../app-designer/Gruntfile.js adbpush
          # adb shell input keyevent 82
          ./gradlew -i --stacktrace connectedSnapshotUitestDebugAndroidTest; s=$?; adb pull /sdcard/opendatakit/default/output/logging logging; (exit $s)

    - name: Upload androidTest results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: androidTest-results-api${{ matrix.api }}
        path: tables/tables_app/build/reports/androidTests
        if-no-files-found: error

    - name: Upload emulator logcat
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logcat.log-api${{ matrix.api }}
        path: tables/logcat.log
        if-no-files-found: error

    - name: Upload default/output/logging
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: default-output-logging-api${{ matrix.api }}
        path: tables/logging
        if-no-files-found: error
